<?php
use CRM_Donrec_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'zwb_donation_receipt_item',
        'table_name' => 'civicrm_value_zwb_donation_receipt_item',
        'title' => E::ts('Donation Receipt Item'),
        'extends' => 'Contribution',
        // '0' to prevent from being shown in the contact dashboard (#2541).
        'style' => '0',
        'collapse_display' => TRUE,
        'is_multiple' => TRUE,
        'is_reserved' => TRUE,
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_contribution_hash',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'contribution_hash',
        'label' => E::ts('contribution_hash'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'contribution_hash',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_exporters',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'exporters',
        'label' => E::ts('exporters'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'exporters',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_currency',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'currency',
        'label' => E::ts('currency'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'currency',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_receive_date',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'receive_date',
        'label' => E::ts('receive_date'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'date_format' => 'mm/dd/yy',
        'column_name' => 'receive_date',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_financial_type_id',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'financial_type_id',
        'label' => E::ts('financial_type_id'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'financial_type_id',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_non_deductible_amount',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'non_deductible_amount',
        'label' => E::ts('non_deductible_amount'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'non_deductible_amount',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_issued_by',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'issued_by',
        'label' => E::ts('issued_by'),
        'data_type' => 'ContactReference',
        'html_type' => 'Autocomplete-Select',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'issued_by',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_total_amount',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'total_amount',
        'label' => E::ts('total_amount'),
        'data_type' => 'Money',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'total_amount',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_issued_on',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'issued_on',
        'label' => E::ts('issued_on'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'date_format' => 'mm/dd/yy',
        'column_name' => 'issued_on',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_receipt_id',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'receipt_id',
        'label' => E::ts('Receipt ID'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'receipt_id',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_issued_in',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'issued_in',
        'label' => E::ts('issued_in'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'issued_in',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_type',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'type',
        'label' => E::ts('type'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'type',
        'option_group_id.name' => 'donrec_type',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_item_CustomField_status',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt_item',
        'name' => 'status',
        'label' => E::ts('status'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'status',
        'option_group_id.name' => 'donrec_status',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
