<?php
use CRM_Donrec_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup_zwb_donation_receipt',
    'entity' => 'CustomGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'zwb_donation_receipt',
        'table_name' => 'civicrm_value_zwb_donation_receipt',
        'title' => E::ts('Donation Receipt'),
        // '0' to prevent from being shown in the contact dashboard (#2541).
        'style' => '0',
        'collapse_display' => TRUE,
        'is_multiple' => TRUE,
        'is_reserved' => TRUE,
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_shipping_postal_code',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'shipping_postal_code',
        'label' => E::ts('shipping_postal_code'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'text_length' => 12,
        'column_name' => 'shipping_postal_code',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_shipping_country',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'shipping_country',
        'label' => E::ts('shipping_country'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'shipping_country',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_shipping_addressee_display',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'shipping_addressee_display',
        'label' => E::ts('Shipping Addressee Display'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'shipping_addressee_display',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_shipping_supplemental_address_1',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'shipping_supplemental_address_1',
        'label' => E::ts('shipping_supplemental_address_1'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'shipping_supplemental_address_1',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_supplemental_address_2',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'supplemental_address_2',
        'label' => E::ts('supplemental_address_2'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'supplemental_address_2',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_city',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'city',
        'label' => E::ts('city'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'city',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_original_file',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'original_file',
        'label' => E::ts('original_file'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'original_file',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_street_address',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'street_address',
        'label' => E::ts('street_address'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'street_address',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_issued_on',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'issued_on',
        'label' => E::ts('issued_on'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'date_format' => 'mm/dd/yy',
        'column_name' => 'issued_on',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_issued_by',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'issued_by',
        'label' => E::ts('issued_by'),
        'data_type' => 'ContactReference',
        'html_type' => 'Autocomplete-Select',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'issued_by',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_status',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'status',
        'label' => E::ts('status'),
        'html_type' => 'Select',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'text_length' => 255,
        'note_columns' => 60,
        'note_rows' => 4,
        'column_name' => 'status',
        'option_group_id.name' => 'donrec_status',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_profile_id',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'profile_id',
        'label' => E::ts('Profile ID'),
        'data_type' => 'Int',
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'profile_id',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_profile',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'profile',
        'label' => E::ts('Profile'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'profile',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_date_from',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'date_from',
        'label' => E::ts('date_from'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'date_format' => 'mm/dd/yy',
        'column_name' => 'date_from',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_addressee_display',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'addressee_display',
        'label' => E::ts('Addressee Display'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'addressee_display',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_date_to',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'date_to',
        'label' => E::ts('date_to'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'date_format' => 'mm/dd/yy',
        'column_name' => 'date_to',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_supplemental_address_1',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'supplemental_address_1',
        'label' => E::ts('supplemental_address_1'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'supplemental_address_1',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_display_name',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'display_name',
        'label' => E::ts('Display Name'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'display_name',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_postal_code',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'postal_code',
        'label' => E::ts('postal_code'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'text_length' => 12,
        'column_name' => 'postal_code',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_contact_type',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'contact_type',
        'label' => E::ts('Contact Type'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'contact_type',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_country',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'country',
        'label' => E::ts('country'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'country',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_gender',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'gender',
        'label' => E::ts('Gender'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'gender',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_shipping_street_address',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'shipping_street_address',
        'label' => E::ts('shipping_street_address'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'shipping_street_address',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_prefix',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'prefix',
        'label' => E::ts('Prefix'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'prefix',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_shipping_supplemental_address_2',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'shipping_supplemental_address_2',
        'label' => E::ts('shipping_supplemental_address_2'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'shipping_supplemental_address_2',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_postal_greeting_display',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'postal_greeting_display',
        'label' => E::ts('Postal Greeting Display'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'postal_greeting_display',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_shipping_city',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'shipping_city',
        'label' => E::ts('shipping_city'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'shipping_city',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_email_greeting_display',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'email_greeting_display',
        'label' => E::ts('Email Greeting Display'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'email_greeting_display',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_exporters',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'exporters',
        'label' => E::ts('exporters'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'exporters',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
  [
    'name' => 'CustomGroup_zwb_donation_receipt_CustomField_receipt_id',
    'entity' => 'CustomField',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => 'zwb_donation_receipt',
        'name' => 'receipt_id',
        'label' => E::ts('Receipt ID'),
        'html_type' => 'Text',
        'is_searchable' => TRUE,
        'is_view' => TRUE,
        'column_name' => 'receipt_id',
      ],
      'match' => [
        'name',
        'custom_group_id',
      ],
    ],
  ],
];
